#! usr/bin/env php
<?php

namespace Creational\AbstractFactory;

require_once 'vendor/autoload.php';

$content     = 'Message';
$xmlFactory  = new XMLFactory();
$jsonFactory = new JsonFactory();

echo $xmlFactory->createMessage($content)->getContent() . "\n";
echo $jsonFactory->createMessage($content)->getContent() . "\n";
