#! usr/bin/env php
<?php

namespace Creational\AbstractFactory;

require_once 'vendor/autoload.php';

$content = 'Message';

echo (new XMLFactory())->createMessage($content)."\n";
echo (new JsonFactory())->createMessage($content)."\n";
