#! usr/bin/env php
<?php

namespace Creational\AbstractFactory;

require_once 'vendor/autoload.php';

$content     = 'Message';
$xmlFactory  = new XMLFactory();
$jsonFactory = new JsonFactory();

$xmlFactory->createMessage($content)->getContent();
$jsonFactory->createMessage($content)->getContent();
